//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EMPLEADOS
    {
        [Display(Name ="#")]
        public int ID_EMPLEADOS { get; set; }
        [Display(Name = "#")]
        public int ID_MAQUINARIA { get; set; }
        [Display(Name = "Nombre")]
        public string NOMBRE { get; set; }
        [Display(Name = " Cargo ")]
        public string CARGO { get; set; }
        [Display(Name = "Cedula") ]
        public Nullable<int> CEDULA { get; set; }
        [Display (Name = "Area")]
        public string AREA { get; set; }
    
        public virtual MAQUINARIA MAQUINARIA { get; set; }
    }
}
