//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MAQUINARIA
    {
        public MAQUINARIA()
        {
            this.EMPLEADOS = new HashSet<EMPLEADOS>();
        }

        [Display(Name ="#")]
        public int ID_MAQUINARIA { get; set; }
        [Display(Name ="serie")]
        public string SERIE_ { get; set; }
        [Display(Name ="Descripcion")]
        public string DESCRIPCION { get; set; }
        [Display(Name ="Estado")]
        public Nullable<bool> ESTADO { get; set; }
    
        public virtual ICollection<EMPLEADOS> EMPLEADOS { get; set; }
    }
}
